apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-deployment
  namespace: beans
  labels:
    app: journal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: journal
  template:
    metadata:
      labels:
        app: journal
    spec:
      containers:
        - name: journal
          image: 2admi/beans-journal:1.0.0
          ports:
            - containerPort: 8002
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: DB_HOST
              value: "mongo-journal"
            - name: DB_PORT
              value: "27019"
            - name: DB_NAME
              value: "beansjournal"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MONGO_DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MONGO_DB_PASSWORD