apiVersion: v1
kind: Service
metadata:
  name: journal-svc
  namespace: beans
  labels:
    app: journal
    type: application
spec:
  selector:
    app: journal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8006
  type: ClusterIP