apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-profile
  namespace: chaos-testing
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - beans
    labelSelectors:
      app: profile
  delay:
    latency: "500ms"
    correlation: "100"
    jitter: "100ms"
  duration: "1m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-order
  namespace: chaos-testing
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - beans
    labelSelectors:
      app: order
  delay:
    latency: "500ms"
    correlation: "100"
    jitter: "50ms"
  duration: "1m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-menu
  namespace: chaos-testing
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - beans
    labelSelectors:
      app: menu
  delay:
    latency: "500ms"
    correlation: "100"
    jitter: "50ms"
  duration: "1m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-loyalty
  namespace: chaos-testing
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - beans
    labelSelectors:
      app: loyalty
  delay:
    latency: "500ms"
    correlation: "100"
    jitter: "50ms"
  duration: "1m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-journal
  namespace: chaos-testing
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - beans
    labelSelectors:
      app: loyalty
  delay:
    latency: "500ms"
    correlation: "100"
    jitter: "50ms"
  duration: "1m"