apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: beans
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 2admi/beans-gateway:0.0.1
          ports:
            - containerPort: 8001
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: JWT_SECRET_KEY
