apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: beans
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP