apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: beans
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: 2admi/beans-order:1.0.0
          ports:
            - containerPort: 8003
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: DB_HOST
              value: "cockroachdb-order"
            - name: DB_PORT
              value: "26257"
            - name: DB_NAME
              value: "order_db"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: ""
            - name: "REDIS_HOST"
              value: "order-redis-svc"
            - name: "REDIS_PORT"
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: REDIS_PASSWORD
