apiVersion: v1
kind: Service
metadata:
  name: order-svc
  namespace: beans
  labels:
    app: order
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003
  type: ClusterIP