apiVersion: v1
kind: Service
metadata:
  name: insight-clickhouse-svc
  namespace: beans
spec:
  selector:
    app: insight-clickhouse
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
  type: ClusterIP
