apiVersion: v1
kind: Service
metadata:
  name: mongo-journal
  namespace: beans
  labels:
    app: mongo-journal
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo-journal
