apiVersion: v1
kind: Service
metadata:
  name: postgres-order
  namespace: beans
spec:
  ports:
    - port: 5433
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-order
  type: ClusterIP
