apiVersion: v1
kind: Service
metadata:
  name: cockroachdb-order
  namespace: beans
spec:
  ports:
    - port: 26257
      name: grpc
    - port: 8080
      name: http
  clusterIP: None
  selector:
    app: cockroachdb-order
