apiVersion: v1
kind: Service
metadata:
  name: postgres-profile
  namespace: beans
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-profile
  type: ClusterIP
