apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-journal
  namespace: beans
  labels:
    app: mongo-journal
spec:
  serviceName: mongo-journal
  replicas: 3
  selector:
    matchLabels:
      app: mongo-journal
  template:
    metadata:
      labels:
        app: mongo-journal
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          command:
            - mongod
            - "--bind_ip_all"
            - "--noauth"
            - "--replSet"
            - "rs0"
          env:
            - name: MONGO_REPLICA_SET
              value: "rs0"
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
