apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-loyalty
  namespace: beans
  labels:
    app: mongo-loyalty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-loyalty
  template:
    metadata:
      labels:
        app: mongo-loyalty
    spec:
      containers:
        - name: mongo-loyalty
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MONGO_DB_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MONGO_DB_PASSWORD
            - name: MONGO_INITDB_DATABASE
              value: loyaltyeventstore
          volumeMounts:
            - name: mongo-data-loyalty
              mountPath: /data/db
      volumes:
        - name: mongo-data-loyalty
          emptyDir: {}
