apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-menu
  namespace: beans
  labels:
    app: mongo-menu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-menu
  template:
    metadata:
      labels:
        app: mongo-menu
    spec:
      containers:
        - name: mongo-menu
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MONGO_DB_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MONGO_DB_PASSWORD
            - name: MONGO_INITDB_DATABASE
              value: beansmenu
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
