apiVersion: v1
kind: Service
metadata:
  name: insight-svc
  namespace: beans
  labels:
    app: insight
    type: application
spec:
  selector:
    app: insight
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8005
  type: ClusterIP