apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: beans
  labels:
    app: kafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
              name: broker
            - containerPort: 9093
              name: internal
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value:  "PLAINTEXT://$(POD_NAME).kafka.beans.svc.cluster.local:9092"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: beans
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      targetPort: broker
      protocol: TCP
  selector:
    app: kafka
  clusterIP: None
