apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  namespace: beans
  labels:
    app: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: 2admi/beans-profile:1.0.0
          ports:
            - containerPort: 8001
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: DB_HOST
              value: "postgres-profile"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "profile_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: JWT_SECRET_KEY
            - name: BARISTA_REGISTRATION_KEY
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: BARISTA_REGISTRATION_KEY
