apiVersion: v1
kind: Service
metadata:
  name: profile-svc
  namespace: beans
  labels:
    app: profile
    type: application
spec:
  selector:
    app: profile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP