apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-deployment
  namespace: beans
  labels:
    app: menu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
    spec:
      containers:
        - name: menu
          image: 2admi/beans-menu:1.0.0
          ports:
            - containerPort: 8002
          env:
            - name: DB_HOST
              value: "mongo-menu-0.mongo-menu.beans.svc.cluster.local:27017,mongo-menu-1.mongo-menu.beans.svc.cluster.local:27017,mongo-menu-2.mongo-menu.beans.svc.cluster.local:27017"
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: "beansmenu"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MONGO_DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MONGO_DB_PASSWORD
            - name: DB_REPLICASET
              value: "rs0"
            - name: REDIS_HOST
              value: "menu-redis-svc"
            - name: REDIS_PORT
              value: "16379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: REDIS_PASSWORD