apiVersion: v1
kind: Service
metadata:
  name: menu-svc
  namespace: beans
  labels:
    app: menu
    type: application
spec:
  selector:
    app: menu
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: ClusterIP